stages:
  - build
  - test

build-job:
  stage: build
  image: node:18
  script:
    - echo "Build berhasil"
    - npm install

test-job:
  stage: test
  image: node:18
  script:
    - echo "Test berhasil"